### ISSUE TITLE
printError is not defined

### ISSUE THREAD

**Issue by makuto** [gulp-community/gulp-terser-js#24]
```
d:\node_modules\gulp-terser-js\index.js:41
      return next(printError(new PluginError('gulp-terser', res.error)));
                  ^

ReferenceError: printError is not defined
    at DestroyableTransform._transform (d:\node_modules\gulp-terser-js\index.js:41:19)
    at DestroyableTransform.Transform._read (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at DestroyableTransform.ondata (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:115:13)
    at DestroyableTransform.emit (events.js:210:7)
    at addChunk (d:\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:284:12)
```

My version:
```
{ npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.2.1',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.13.1',
  v8: '5.8.283.41',
  zlib: '1.2.11' }
```

My Package.json:
```
{
  "name": "site-builder",
  "version": "1.0.0",
  "description": "Build site",
  "main": "index.js",
  "scripts": {
    "test": "echo \"No test command\"",
    "buildHouse": "gulp houseBuildAll",
    "buildRelease": "gulp releaseBuildAll",
    "devWatcher": "gulp houseBuildThenDevWatcher"
  },
  "author": "My Site",
  "license": "ISC",
  "devDependencies": {
    "browser-sync": "^2.18.13",
    "child-process": "^1.0.2",
    "crc32": "^0.2.2",
    "gulp": "^3.9.1",
    "gulp-changed": "^3.1.0",
    "gulp-csso": "^2.0.0",
    "gulp-expect-file": "0.0.7",
    "gulp-filter": "^5.0.1",
    "gulp-html-beautify": "^1.0.1",
    "gulp-htmlmin": "^3.0.0",
    "gulp-if": "^2.0.2",
    "gulp-index": "0.0.8",
    "gulp-nunjucks-render": "^2.2.1",
    "gulp-plumber": "^1.1.0",
    "gulp-print": "^2.0.1",
    "gulp-terser-js": "^4.0.0",
    "gulp-typescript": "^5.0.1",
    "merge-stream": "^2.0.0",
    "run-sequence": "^2.1.0",
    "typescript": "^3.5.2"
  },
  "false": {},
  "dependencies": {}
}
```

My usage:
```
var terser = require('gulp-terser-js');

function buildScriptsTask(rebuildAll = true, releaseBuild = false) {
    return gulp.src(sourceUIFolder + '/**/*.js')
        .pipe(filter(['**', '!**/*_Global.*']))
        .pipe(gulpif(!rebuildAll, plumber()))
        .pipe(gulpif(!rebuildAll, changed(outputFolder + uiFolder)))
        .pipe(print(printFormat))
        .pipe(nunjucksRender(nunjucksOptions))
        .pipe(messageGenerator.generateMessages(outputFolder + uiFolder, rebuildAll))
        .pipe(gulpif(releaseBuild, terser()))
        .pipe(gulp.dest(outputFolder + uiFolder));
}

gulp.task('releaseBuild_Scripts_All', function() {
    return buildScriptsTask(rebuildAll = true, releaseBuild = true);
});

gulp.task('releaseBuildAll', function(done) {
runSequence('makeDestWritable',
           ['releaseBuild_Html_All',
            'releaseBuild_Scripts_All',
            'releaseBuild_Styles_All',
            'releaseBuild_SharedScripts_All',
            'releaseBuild_SharedStyles_All'
        ],
        'saveMessages_All',
        'buildIndex'
        );
}
//...
```

**Comment by makuto** [comment]
Node version `8.2.1`

**Comment by A-312** [comment]
Hi can you upgrade terser in [4.1.1](https://github.com/gulp-community/gulp-terser-js/blob/master/CHANGELOG.md#411---2019-08-13) ?

Also the last version should be good : 5.2.2 (We support the [node version 8.15](https://travis-ci.com/github/gulp-community/gulp-terser-js/jobs/330751455) maybe before).

**Comment by makuto** [comment]
Upgrading to 5.2.2 fixed the issue. Thank you!
